name: Build Gato Windows Executable
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install gato and dependencies
        run: |
          python -m pip install --upgrade pip
          # Install explicit dependencies
          pip install colorama requests pyyaml packaging cryptography py7zr rarfile tqdm
          # Install gato and its dependencies
          pip install -e .
          # Install PyInstaller
          pip install pyinstaller
      - name: Build executable
        run: |
          # Create a simple entry point script
          echo 'import sys; from gato.main import entry; entry()' > gato_launcher.py
          # Use this entry script for PyInstaller
          pyinstaller --onefile --name gato_windows_amd64.exe gato_launcher.py
      - name: Create zip file
        run: |
          Compress-Archive -Path .\\dist\\gato_windows_amd64.exe -DestinationPath gato_windows.zip
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gato-windows
          path: gato_windows.zip
