name: Test and Lint
on: 
    push:
    pull_request:

jobs:
    Linux-test-and-lint:
        name: Ubuntu Linux Test and Lint
        runs-on: ubuntu-latest
        strategy:
          matrix:
            python-version: ["3.8", "3.9", "3.10"]

        timeout-minutes: 10

        steps:
          - name: Checkout the repo
            uses: actions/checkout@v3
          - name: Setup python
            uses: actions/setup-python@v4
            with:
              python-version: ${{ matrix.python-version }}
          - run: |
              python -m pip install --upgrade pip
              pip install ".[test]"
          - name: Lint with flake8
            run: |
              # stop the build if there are Python syntax errors or undefined names
              flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
              # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
              flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          - name: Test with Pytest
            run: |
              pytest --cov-fail-under=80

    OSX-test-and-lint:
        name: OS X Test and Lint
        runs-on: macos-latest
        strategy:
          matrix:
            python-version: ["3.8", "3.9", "3.10"]

        timeout-minutes: 10

        steps:
          - name: Checkout the repo
            uses: actions/checkout@v3
          - name: Setup python
            uses: actions/setup-python@v4
            with:
              python-version: ${{ matrix.python-version }}
          - run: |
              python -m pip install --upgrade pip
              pip install ".[test]"
          - name: Lint with flake8
            run: |
              # stop the build if there are Python syntax errors or undefined names
              flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
              # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
              flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          - name: Test with Pytest
            run: |
              pytest --cov-fail-under=80
